import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import Welcome from "../components/welcome";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fantasy Payments</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="Alchemy University Final Project"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Layout>
        <Welcome />
      </Layout>
    </>
  );
};

export default Home;
